# Hot Tips: 2016-09-08

## Capstones Begin

Now that we're fully in the capstone part of the class, we'll transition to a set schedule:

1. Daily Trello stand-ups at 9:45 A.M.
1. Advanced material intro / Hot Tips right after lunch at 1:30 P.M.
1. One-on-one Mondays
1. Show-and-tell Fridays at 11 A.M.

I have made a Trello team and [boards](https://trello.com/dayclass20160707) for each of your projects.
I'd like you to start keeping track of which tasks are left for your MVP, which you are currently working on currently, and which are complete.
You'll be in charge of adding and moving tasks around the board.
I will open up each board on the projector during your time at standup and you can give us an update on what it says you're working on.

Show-and-Tell Fridays will be getting on the projector and spending 10 minutes showing off the code and features you've been working on, and soliciting help.

If you have advanced topics you'd like me to talk about, let me know!

## Look at Solution

I put up one new practice problem solution.

* [Ice Cream Poll](/practice/solutions/ice_cream_poll)

## Instantiate Exceptions

Exceptions _are classes_.
They should be instantiated with a message describing the error.
There is a deprecated old syntax that lets you skip the construction call, but avoid that.

Avoid:

```py
if not is_phone_valid(phone_number):
    # Note no parentheses `()`
    raise ValueError
```

Instead:

```py
if not is_phone_valid(phone_number):
    raise ValueError('phone number is invalid: {!r}'.format(phone_number))
```

## Exceptions and None vs. Empty

Don't throw an exception or return None when the empty list or empty string or empty set will do.
Just because you'd say "none" in English to describe the result doesn't mean it's better for your functions to return.

It _requires_ all dependent code to be more verbose.

Avoid:

```py
def get_flutts_with_string(query_string):
    matching_flutts = models.Flutt.objects.filter(text__contains=query_string)
    if len(matching_flutts) < 1:
        return None
    else:
        return matching_flutts


rabbit_flutts = get_flutts_with_string('rabbit')
if rabbit_flutts is None:
    rabbit_flut_users = None
else:
    rabbit_flut_users = set(flutt.user for flutt in rabbit_flutts)

if rabbit_flut_users is None:
    print('No users talked about rabbits.')
else:
    user_list_str = ', '.join(rabbit_flut_users)
    print('Users {} talked about rabbits.'.format(user_list_str))
```

Instead:

```py
def get_flutts_with_string(query_string):
    return models.Flutt.objects.filter(text__contains=query_string)


rabbit_flutts = get_flutts_with_string('rabbit')
rabbit_flut_users = set(flutt.user for flutt in rabbit_flutts)

if len(rabbit_flut_users) < 1:
    print('No users talked about rabbits.')
else:
    user_list_str = ', '.join(rabbit_flut_users)
    print('Users {} talked about rabbits.'.format(user_list_str))
```

Same thing happens with exceptions.

## Fight 2: Exceptions vs. Multi-Type Return

Prefer throwing exceptions rather than returning multiple semantically unrelated types from a function.
If you return `None` or `False` or a special string, they can be silently passed around the program and only blow up when you _use them_, not when you _make them_.

Avoid:

```py
def get_user_by_name(user_name):
    if does_user_exist(user_name):
        return ...
    else:
        return None

user_name = get_user_by_name('david')
# Something deep inside this line could throw an TypeError, but isn't where the "error" was.
# Makes debugging hard.
do_something_complicated_with_user_name(user_name)
```

Instead:

```py
def get_user_by_name(user_name):
    if does_user_exist(user_name):
        return ...
    else:
        raise LookupError('no user with name {!r}'.format(user_name))

# This line throws an exception and shows where the true issue is.
# Yeah, I still need to handle it, but it's easier to know where to put logic.
user_name = get_user_by_name('david')
do_something_complicated_with_user_name(user_name)
```

## Avoid "Casting" Exceptions Unnecessarily

Exceptions have a lot of useful information inside of them: exception type, message, originating line, traceback.
Whenever you re-raise an exception, you might lose that information.

Avoid:

```py
try:
    models.Flutt.get(id=5)
except models.Flutt.DoesNotExist:
    raise KeyError('could not find flutt')
```

That hides the actual line that was troublesome and ends up raising an error that's less precise than the original.
It's okay to have custom exceptions.

The only instance in which this is okay to do is when the exception that is being thrown is misleading.

```py
USER_ID_TO_NAME = {}

def lookup_initials_of_name(user_id):
    try:
        name = USER_ID_TO_NAME.get(user_id)
        # name might be None, which doesn't have .split()
        return [word[0] for word in name.split()]
    # Don't raise TypeError since that implies something was wrong with a variable type.
    # Instead something was actually wrong with a lookup.
    except TypeError:
        raise LookupError('no user with ID {!r}'.format(user_id))
```

## Decorators

I wrote up [some notes](/notes/py-decorators.md) on decorators.
